"""remove all source_stats

Revision ID: d32631441145
Revises: 7a173aa35c52
Create Date: 2020-06-14 20:36:53.428933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd32631441145'
down_revision = '7a173aa35c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_stats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('town_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shelf_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crate_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('production_time_reduction_fraction', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exp_point_increase_fraction', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name='source_stats_source_id_fkey'),
    sa.ForeignKeyConstraint(['town_id'], ['town.id'], name='source_stats_town_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='source_stats_pkey')
    )
    # ### end Alembic commands ###
