"""user_avatar_hash

Revision ID: e1eb70ef837a
Revises: b1c93b937353
Create Date: 2020-06-02 20:13:32.765018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1eb70ef837a'
down_revision = 'b1c93b937353'
branch_labels = None
depends_on = None




def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()




#--------------------------------
# Default
def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


#--------------------------------
# Township
def upgrade_township_data():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_township_data():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


#--------------------------------
# User
def upgrade_user_data():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade_user_data():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
